### PR TITLE
Ci fixes no plugin

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e999c59e5a0faed218a433a550025239/raw/310fc4e6ea59999b6a7fde0ea0905f6040700b6a/run_nccl_test.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e999c59e5a0faed218a433a550025239/raw/8625983da4199cde86b30f99064adb0e229818c1/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/e999c59e5a0faed218a433a550025239/raw/65a4d007ec233bfaa750e31aa2b1ba62aad11c04/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/e999c59e5a0faed218a433a550025239/raw/1626e0fd6f69a9cbfeadbe1b9db891a03427a1dc/configure_sharp_startup.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/d6835e9bb11bb2161015ce0c56914482/raw/3b794c4cfb04dd55713e5a4aa6936870428097ed/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/d6835e9bb11bb2161015ce0c56914482/raw/4b6517b9d0575340230be71a5c71c7b212348292/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/d6835e9bb11bb2161015ce0c56914482/raw/643d45e969104a08c78870b08de504b289b2ace9/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/d6835e9bb11bb2161015ce0c56914482/raw/03161cf051191ca8afa1ba37da7dfe467eb4b9a1/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/d6835e9bb11bb2161015ce0c56914482/raw/8412ec4215b1f6d973378965d48d6185f628d0b5/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/98fae10c5b5551734ff66fd258c9e8d4/raw/e71b9ee1592707ccb6745b1c0687088967a42211/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/98fae10c5b5551734ff66fd258c9e8d4/raw/65a4d007ec233bfaa750e31aa2b1ba62aad11c04/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/98fae10c5b5551734ff66fd258c9e8d4/raw/df96633b3983f94652aaf06c47ed0cee1f9238b7/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/98fae10c5b5551734ff66fd258c9e8d4/raw/cfe55b6a9f641dd2ac05f26f06457f90fa9a7b40/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/98fae10c5b5551734ff66fd258c9e8d4/raw/84b36e1e2fdf3c6b478fc391819dcff13adb27ca/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
