### PR TITLE
Enabled SHARP configuration and related test scenarios

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/46abef40780123d465f5c30aae7f6b57/raw/587e097f22813a9f1db28eea0d16866e39df313b/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/46abef40780123d465f5c30aae7f6b57/raw/9345aac622e2db39113ce7779a3420b6d0bf201a/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/46abef40780123d465f5c30aae7f6b57/raw/d469e38e1a146b8c46ffaf6640cba33d613f1b2c/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/fbfde01f2793752f9a4d26f93cae3d0a/raw/6099b015d917aac2a82cf9ceecc735ca8e54ee89/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/fbfde01f2793752f9a4d26f93cae3d0a/raw/dd9142b5b90a9f3b1ffaff269bf1d6d24e3eda7d/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/fbfde01f2793752f9a4d26f93cae3d0a/raw/a8e78000cab65b5c692929e512988db6067d52a7/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/0fc0f3caa7c3a0dd89511675d8e34059/raw/32424b220278a960ec33d6da06d77ccb0d5d020e/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/0fc0f3caa7c3a0dd89511675d8e34059/raw/a821aaaaabfdf57fc392fc15c463f14bfe397cea/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/0fc0f3caa7c3a0dd89511675d8e34059/raw/2f9dffbaaa1f4e7b0abfc57eed3cca8f81748b3b/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/f3330bf93aab3a05e853099907a7b78e/raw/98dd1942c491657eb8d5fc88a41d663ca224f52b/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/f3330bf93aab3a05e853099907a7b78e/raw/707f76b5f8054e62a636a92c800cd9c3bcbb66a0/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/f3330bf93aab3a05e853099907a7b78e/raw/e0c3d48d47a18e4fc570278d72d53f272a450890/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/90f3034748e5d8f61a04ec8c2f72ca9b/raw/1d558bbe3150a12f1c2f11b3f4e3d1b3ff57c2f5/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/90f3034748e5d8f61a04ec8c2f72ca9b/raw/707f76b5f8054e62a636a92c800cd9c3bcbb66a0/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/90f3034748e5d8f61a04ec8c2f72ca9b/raw/19b130d15028ffca7a697a1b48a0863dcc184a4e/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/c5fd9be47ec41eae860cb1caaf350b55/raw/3127c8482e4e581b5b43ebc41106461bd4e0515f/configure_sharp_startup.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/c5fd9be47ec41eae860cb1caaf350b55/raw/707f76b5f8054e62a636a92c800cd9c3bcbb66a0/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/c5fd9be47ec41eae860cb1caaf350b55/raw/57a6feaba78eec891a0eaca838cba797b7ff4165/build_nccl.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/44f0fd334e523b377f087807936ec234/raw/34d055589f9ae5bdd426f849f23a543131cfcf32/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/44f0fd334e523b377f087807936ec234/raw/7622a07a2047c8e7a0ba748807374c6caf561867/build_nccl.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/44f0fd334e523b377f087807936ec234/raw/cd3aaa18821980e08f5f2cf6227cae920939e381/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/44f0fd334e523b377f087807936ec234/raw/45bac0c3e09f65d1317ee3d449813198b43c581b/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/44f0fd334e523b377f087807936ec234/raw/1008a48ff1d5e6fb9c72cf2c264723e63f97caa9/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/18f4dfe3f64eebad890327d9bff134a2/raw/707f76b5f8054e62a636a92c800cd9c3bcbb66a0/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/18f4dfe3f64eebad890327d9bff134a2/raw/7508f4c79763188cc848dafba34cabc27090034d/build_nccl.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/18f4dfe3f64eebad890327d9bff134a2/raw/824cc6a3495e08c1e44136dde5e15c9ae151cb97/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/18f4dfe3f64eebad890327d9bff134a2/raw/e43168617b8d4da6d3f34cff319586eaffc1dfe5/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/18f4dfe3f64eebad890327d9bff134a2/raw/9f2288b97af9109376fe8aa3eaf115dc1e318673/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/7f088d5852e7c535cea522fc309bb973/raw/062d5433f943e9f8f017633ea1505b59766826f1/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/7f088d5852e7c535cea522fc309bb973/raw/c1b42324c4ac214ac77fa6904babcddb384488f0/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/7f088d5852e7c535cea522fc309bb973/raw/acc98974c290816ddb5c60f2127bb02d0d4a74d4/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/7f088d5852e7c535cea522fc309bb973/raw/92372f5487a4f1fabe7e7ec9ae08869f17ba5925/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/7f088d5852e7c535cea522fc309bb973/raw/015eb200d64901deeb1263448cc8298a9f63d322/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/0650983a87e06833767dcc093883c161/raw/16244085afc771ba5e5da9bea49e7298db15e2a2/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/0650983a87e06833767dcc093883c161/raw/2ac306572cb4be649f5b860c2364c52f052ed518/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/0650983a87e06833767dcc093883c161/raw/d8dca82890f12ff09f1b965f7a871124f78c549f/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/55ee699434448f6134a5476f81afa224/raw/5b77ac9e08f964839188a782fd7b3aca1b189e1b/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/55ee699434448f6134a5476f81afa224/raw/dcbac55d511bc30f0dff4a920fdc99e9d1e5cbff/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/55ee699434448f6134a5476f81afa224/raw/9ab81f93b131bf53e88b7093e16ee0cd827f6f18/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/55ee699434448f6134a5476f81afa224/raw/eac5c1caceb45f3cdde4a1b0d7b04f19311f0f65/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/55ee699434448f6134a5476f81afa224/raw/629ca963cc549dc7e920177c5e6c5e4df13d002d/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/1fef38926c14e720ba727d1b04c3fcd5/raw/9a7f7ac398e28c0be736049c951f5395b24c5722/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/1fef38926c14e720ba727d1b04c3fcd5/raw/fe18c60d2e511d36e09c2024f7b28e82dcbd95e5/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/1fef38926c14e720ba727d1b04c3fcd5/raw/9e87e30a656f0abfa4bc15f73e44cca4a3f72625/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/1fef38926c14e720ba727d1b04c3fcd5/raw/ce93e43055b83431311affb878c478f53aea9429/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/f6936f00faa7e78e78892afb91aebc02/raw/d92cc807f4cdfec92b790835fa822d47abda2348/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/f6936f00faa7e78e78892afb91aebc02/raw/3b3dec8da54394810f62dd4f3a477cdd502dfafc/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/f6936f00faa7e78e78892afb91aebc02/raw/07e8756450303e81cd18dd28a9514e9313a988aa/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/cc30551a65727bc97c1d76357575c5f1/raw/2278b96843517e81211f09a8021937158f5a41ac/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/cc30551a65727bc97c1d76357575c5f1/raw/3417ecc06c45cce11901dd1957ec017c8f176b6d/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/cc30551a65727bc97c1d76357575c5f1/raw/e1739121c2e910c45861c7a939eab026b48dfa82/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e078158b84af1ba36a5910ff2715a229/raw/037be0f34485187d487c50b193af8ce456cfd044/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/e078158b84af1ba36a5910ff2715a229/raw/07e8756450303e81cd18dd28a9514e9313a988aa/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/e078158b84af1ba36a5910ff2715a229/raw/5f8c4372d43e35980dae22fe7c3da18525691903/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/e078158b84af1ba36a5910ff2715a229/raw/3f31d00d4a42e292f8ad77efa8c27cd7df682c86/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e078158b84af1ba36a5910ff2715a229/raw/4ee6f548309ab50992bca4492f8df31a6d243f60/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/69e831f73e4f2f2454ab41675c9aeab1/raw/42457acf8a3ff8d2ecbca052fc1d4c6a2b290bd9/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/69e831f73e4f2f2454ab41675c9aeab1/raw/07e8756450303e81cd18dd28a9514e9313a988aa/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/69e831f73e4f2f2454ab41675c9aeab1/raw/24e22df9c9cc701e1e28bdcb7c74a2f3873e63f7/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/69e831f73e4f2f2454ab41675c9aeab1/raw/46b11c9802dd90aa55ca77c5f8a5252e906d8d5d/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/69e831f73e4f2f2454ab41675c9aeab1/raw/89030d6770f2d4a472c622de5791655572f0cbee/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/df21e42dee90cf8bb5a1a9b67016750b/raw/bc388025d8e5964bcd1d0cb074b98f6ac6f0961b/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/df21e42dee90cf8bb5a1a9b67016750b/raw/b146a1844421e54a47c0c3446a0abaf8ab060daf/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/df21e42dee90cf8bb5a1a9b67016750b/raw/068714beb1e9a4db3ca3acf93a3af4e36a04e984/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/df21e42dee90cf8bb5a1a9b67016750b/raw/7071709d1cc42b79ca2505a3539badb7b87b8f4f/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/df21e42dee90cf8bb5a1a9b67016750b/raw/5a9d2b59ab57e781709c882077b4b2074910a7ad/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/5ebbe0d923f9271ffd3bc1f1a4e96fcd/raw/ce052a5116df341da14ec7402abc8debabec7708/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/5ebbe0d923f9271ffd3bc1f1a4e96fcd/raw/b146a1844421e54a47c0c3446a0abaf8ab060daf/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/5ebbe0d923f9271ffd3bc1f1a4e96fcd/raw/d683439f2328848a76d05c556e91a841a0b9e4ab/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/5ebbe0d923f9271ffd3bc1f1a4e96fcd/raw/0fdcae7467d6a25f07b711ea90c820b884d7b09f/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/5ebbe0d923f9271ffd3bc1f1a4e96fcd/raw/b67a930300218d944f63ac02feb8d5ed2f10d01c/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/c44fe47fe28d426002d4c460a59d18cf/raw/6f599e97839997de3b17d13d10cb55d050d32af1/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/c44fe47fe28d426002d4c460a59d18cf/raw/bffd11634abf48876a7885e9d217098964afe15c/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/c44fe47fe28d426002d4c460a59d18cf/raw/6f16d079fb716f635e02cbea2a3e24d376008e4b/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/c44fe47fe28d426002d4c460a59d18cf/raw/f5064e8bf56f15fbfc7aead8fe9dcb6831db0177/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/c44fe47fe28d426002d4c460a59d18cf/raw/4d8a2fda561a0cb54db612921ac2c9453b86afe1/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 13-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/7ad67b0fc950fb322ee120f9d6691aa0/raw/4d445ae9d2aaa7dc3c51623e72e9394d8b0f767d/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/7ad67b0fc950fb322ee120f9d6691aa0/raw/259de91f772584a27cd62ece5a7321bbbe967c63/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/7ad67b0fc950fb322ee120f9d6691aa0/raw/073c7208db2b7cdf1244e4f9fbf802d455f1f7e4/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/7ad67b0fc950fb322ee120f9d6691aa0/raw/8f5741f6c08464e4780858e9ae8715c8aff8ce9e/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/7ad67b0fc950fb322ee120f9d6691aa0/raw/b02d93c748f7471a02c5320e49be45152a418a42/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 16-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/87b5120cb462bebd027f94102897c77d/raw/9518f43c5ba2fe280e3a5cd82bec015ad3780386/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/87b5120cb462bebd027f94102897c77d/raw/1f59ece9367c9cb587ec2458f2473ce1a0cb6c7c/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/87b5120cb462bebd027f94102897c77d/raw/181423d2b0efbaa15de10f2402d7fa354be19857/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 16-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/0a5cd37d4df1039f13d7ecbd496102f8/raw/85e1e260fecf2c6b4a2d9df54cfd98ccf7b81230/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/0a5cd37d4df1039f13d7ecbd496102f8/raw/7c020b01b51d557d70a7229446efbfdd6381e1d3/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/0a5cd37d4df1039f13d7ecbd496102f8/raw/181423d2b0efbaa15de10f2402d7fa354be19857/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 16-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/c31b92f12af385eb7f33c7d4a8a519e6/raw/c114b3b45ce2c7a87a04ac869b4f13122ac63978/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/c31b92f12af385eb7f33c7d4a8a519e6/raw/181423d2b0efbaa15de10f2402d7fa354be19857/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/c31b92f12af385eb7f33c7d4a8a519e6/raw/d477936a2b6fff14c04099ddd9a1cfaaae00e8a1/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/c31b92f12af385eb7f33c7d4a8a519e6/raw/481e06ca513c4a2d45bb3808d05dd477067e85cd/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/c31b92f12af385eb7f33c7d4a8a519e6/raw/c49c4c8c4913b372744d5ddf902c04b86d66fcb7/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
