### PR TITLE
CI tester

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 11-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/1fcaa58cd7f867f04398ecf2b31a0aae/raw/04815f3c3dd6c6cec8284b001bb9cef730fd3d6a/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/1fcaa58cd7f867f04398ecf2b31a0aae/raw/a54bf2077406ed3074949111243a21a2e7b14418/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/1fcaa58cd7f867f04398ecf2b31a0aae/raw/4632c2a9f4d3465bd7d94defde086e2d72c024b3/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Pull request closed without merging**
