### PR TITLE
Sharp sanity non blocking colls

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/6a94f0cb64d6c166f6c5f5da4ad86dfb/raw/a2b6699f7d34558563872b2084f353088d2e7511/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/6a94f0cb64d6c166f6c5f5da4ad86dfb/raw/0340a631207a38d4ae1f46c553169f2c3de63f49/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/6a94f0cb64d6c166f6c5f5da4ad86dfb/raw/91b6aa503ccaade814a9c122f81339f408bfa900/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/42e1f4415003019baf2927f4dcdce5fd/raw/6e7c758336e4155d19a2495f08ea2b61f069605e/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/42e1f4415003019baf2927f4dcdce5fd/raw/d5c5ff6d796d24cb4c039fcd69e8eb66a34accbf/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/42e1f4415003019baf2927f4dcdce5fd/raw/9d11a9a07c0587190895f37fc21b5400ad1bab66/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/365be6f38e86dbbb05aea2ed092fb9ce/raw/abc1bd5b3d63c3bc69b4588c40bb739e10eafd9b/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/365be6f38e86dbbb05aea2ed092fb9ce/raw/f64ae928add249c8196b34cc8ba4ca004e06051d/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/365be6f38e86dbbb05aea2ed092fb9ce/raw/9a15472d5d60bca46ba851d8daf2c02a8075420e/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/365be6f38e86dbbb05aea2ed092fb9ce/raw/2d58b2180db2fcbc4c847907f8c6f5f8b1ea0eb0/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/365be6f38e86dbbb05aea2ed092fb9ce/raw/c9ff035037271c44d795fc8403f2cff45c4f49a8/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 18-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/54560e36a6cebbf53043ad7397456eda/raw/042e7b75072f3af72491bdfff8f898021caf2259/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/54560e36a6cebbf53043ad7397456eda/raw/2e9901658b632070415e0167232d4b876aedd08f/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/54560e36a6cebbf53043ad7397456eda/raw/ee6face4d570e8126f292653b063deaa3916ed58/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/54560e36a6cebbf53043ad7397456eda/raw/79ff5ff6e7292c26718d34fa8679b8db11fe4161/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/54560e36a6cebbf53043ad7397456eda/raw/921a5846e9370d748a6ba37aed54a3af7f0ccf4d/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 18-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/83d077e678c8fcde0fb47f37edb3fa5c/raw/2235ce11d1610a4043547f956e748ea2ee392968/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/83d077e678c8fcde0fb47f37edb3fa5c/raw/466c3f3cec5e93c7742e27e9954bd08f499e550d/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/83d077e678c8fcde0fb47f37edb3fa5c/raw/0b82c150a3a84b4748e6d13429111275c1aac459/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/83d077e678c8fcde0fb47f37edb3fa5c/raw/7a64e4cae21715a261c365ff53e99643ada77d87/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 18-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/5dd46b8d62b6720940f57a193ab031c6/raw/dbeda409bb3a58f400cde7817d6bc700b37912c5/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/5dd46b8d62b6720940f57a193ab031c6/raw/ab1404512590281ec433e86b4a26f9782e31401a/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/5dd46b8d62b6720940f57a193ab031c6/raw/8096469ded2ade19ac791d9bbca18add317a4100/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/5dd46b8d62b6720940f57a193ab031c6/raw/49415a038a1ba6d53894663a10b6938ed8b299cb/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Pull request closed without merging**
